### ISSUE TITLE
namemap public API

### ISSUE THREAD

**Issue by tardyp** [DanielT/a2lfile#19]
Hi,
First of all, thanks for this crate, it makes a2l a bit less hateable.

First thing I do to use the crate is to index most things by name as everything is referencing each other by name.

then I realized a2lfile includes a namemap, which already does that thing for me. 
then I realize its private for the checker utility.

I wanted to just submit a PR making it pub, but then the interface with the log_msg might not be the best.

Can we think of a proper api?

**Comment by DanielT** [comment]
Hi,

I'm happy to hear that the crate is useful to you!

I have no problem adding an API to export the functionality.
It could be as simple as having a public `fn build_name_map() -> ModuleNameMap` in the A2lFile struct.

One concern I have - the ModuleNameMap stores references to each item (rather than indexes). This means the borrow checker will prevent you from mutating any of these items. Basically, as long as the namemap exists, the a2l data is read-only.
Would that be a problem for you?

**Comment by tardyp** [comment]
At the moment, my usecase is just read only. So this would be fine.

A further improvement might be to just store all those data with an indexmap so that we can keep the order of original a2l file, while being able to efficiently search by id.

https://docs.rs/indexmap/latest/indexmap/

**Comment by DanielT** [comment]
I exported the the ModuleNameMap struct and also added it to the API of the Module struct.
Now you can do
```rust
let namemmap = a2lfile.project.module[0].build_namemap();
```

**Comment by tardyp** [comment]
Thanks Daniel!

Le ven. 29 sept. 2023, 21:46, Daniel Thaler ***@***.***> a
écrit :
