### ISSUE TITLE
Question about Parsing and Usage of A2ML Structs and IF_DATA

### ISSUE THREAD

**Issue by akikaede6** [DanielT/a2lfile#34]
Hello,

I am new to XCP and recently came across your library. I think it's very well-written. However, I have some questions regarding its usage and would appreciate your help.

In the parsing process, the struct in A2ML is parsed into a string. From my understanding, A2ML declares the struct, which is then used and assigned within `IF_DATA` in entities like `MEASUREMENT`. Can these two be used together? Additionally, will the assignment within `IF_DATA` affect the content of the command?

In the XCP protocol layer, for example, `WRITE_DAQ` does not define fields related to `IF_DATA`. What is the purpose of assigning values to IF_DATA fields?

PS: There is a typo in the `readme`. `A2LError` should be `A2lError`.

Thank you!

**Comment by DanielT** [comment]
Hello,

I'm not sure I fully understand your question - or rather, it seems to me that your understanding of IF_DATA is so incomplete that the question doesn't entirely make sense.

`IF_DATA` provides a way for tools to extend the information in the `A2L` file with tool-specific information.
The `A2ML` describes the format of the `IF_DATA` blocks in the file, which allows automatic validation.

`IF_DATA` is meta-data, so it can't be read or modified itself using `WRITE_DAQ` - it is present in the A2L file, and it is used by the measurement tool, but it is not present on the target device.

The A2L standard does not define the content of any `IF_DATA` blocks, but the content of the `XCP` and `XCPplus` blocks is defined by the ASAM XCP standard. If you wanted to write a calibration tool yourself, it would be completely valid for you to define a `AKIKAEDA6` block, which contains all the information you need in order to connect in any order you prefer, and any A2L file using this definition would still be a valid A2L file.

I hope this helps.

**Comment by akikaede6** [comment]
Thank you for your response. I previously didn't realize that the `XCP` and `XCPPlus` blocks are defined within the protocol, which caused some confusion about how measurement tools retrieve parameters like `CAN ID`.

Given that `IF_DATA` can include custom data structures, I'm curious about how measurement tools interpret these custom fields. While the `XCP` and `XCPPlus` blocks are protocol-defined, how do measurement tools understand the purpose and usage of fields in custom data structures that I might add? If you have any links or resources that address this topic, I would greatly appreciate it.

Also, in this parsing tool, for example, the `OPTIONAL_CMD` field in the `PROTOCOL_LAYER` of `XCPplus` is parsed as a `GenericIfData` type. I can only get the command name of `OPTIONAL_CMD`, such as `GET_ID`. Is there a way to retrieve the corresponding enum values within the block?

Thanks again for your help.

**Comment by DanielT** [comment]
Tools that work with A2L files typically don't read arbitrary `IF_DATA` blocks, but only those that are standardized (`XCP`, `XCPplus`) or defined by the tool itself (e.g. Canape reads `CANAPE_EXT`, etc.)

A2lfile handles this using a procedural macro: `a2ml_specification!`. The A2ML inside the macro is parsed during compilation, and then a module containing data structures for each of the A2ML elements is created in your code.

For example, assume you have `mod ifdata`, represented by ifdata.rs, which contains the following macro invocation:
```rust
a2ml_specification! {
    <ModuleNameToGenerate>

    block "IF_DATA" taggedunion if_data {
        "XCP" struct {
            //...
        }
    }
}
```

This creates the module ifdata::ModuleNameToGenerate, which contains a struct XCP (with all details omitted here).
Now you can use it in your code:

``` rust
use crate::ifdata::ModuleNameToGenerate;

if let Some(decoded_ifdata) = ModuleNameToGenerate::load_from_ifdata(ifdata) {
    // ifdata was decoded, but might not contain XCP info if you allow more blocks in your definition
    if let Some(xcp) = &decoded_ifdata.xcp {
        print_xcp(xcp);
    }
}
```

You can see fully functional examples of this in the a2ltool code:
The ifdata definition: [ifdata.rs](https://github.com/DanielT/a2ltool/blob/master/src/ifdata.rs)
Using the generated data structures to extract XCP information: [xcp.rs](https://github.com/DanielT/a2ltool/blob/861532d3ac58b17d56a02b9d1ce73606bfbb5a7e/src/xcp.rs#L29)
